### ISSUE TITLE
Two LocationForms in the same template

### ISSUE THREAD

**Issue by Ebtessam** [dpnova/django-simple-cities#1]
You can't have two location forms in the same template, probably because of the smart selects

**Comment by dpnova** [comment]
I haven't tried this myself, but have you looked at using the prefix option in django?

https://docs.djangoproject.com/en/dev/ref/forms/api/#django.forms.Form.prefix

**Comment by Ebtessam** [comment]
Yeah was going to try that now, thanks alot for the library!

**Comment by Ebtessam** [comment]
Will close issue if it works.
